apiVersion: v1
kind: Secret
metadata:
  name: cdp-gitlab-secret-{{ .Release.Name  | trunc 35}}
  annotations:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  type: Opaque
stringData:
