apiVersion: v1
kind: Secret
metadata:
  name: cdp-vault-secret-
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-9999"
    "helm.sh/hook-delete-policy": before-hook-creation
  type: Opaque
stringData:
