apiVersion: v1
kind: Secret
metadata:
  name: cdp-vault-secret-{{ .Release.Name }}
  annotations:
    app: {{ template "charts.name" . }}
    chart: {{ template "charts.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  type: Opaque
stringData:
